const USER_CURRENTCITY = 'USER_CURRENTCITY'
const GET_HOMEAD = 'GET_HOMEAD'
const SAVE_HOMEAD = 'SAVE_HOMEAD'
const SAVE_LIKELIST = 'SAVE_LIKELIST'
const SET_ISLOADINGLIKELIST_FLAG = 'SET_ISLOADINGLIKELIST_FLAG'
const GET_DETAIL_INFO = 'GET_DETAIL_INFO'
const GET_COMMENT_LIST = 'GET_COMMENT_LIST'
const GET_ORDER_LIST = 'GET_ORDER_LIST'

export {
    USER_CURRENTCITY,
    GET_HOMEAD,
    SAVE_HOMEAD,
    SAVE_LIKELIST,
    SET_ISLOADINGLIKELIST_FLAG,
    GET_DETAIL_INFO,
    GET_COMMENT_LIST,
    GET_ORDER_LIST
}